### ISSUE TITLE
Morning session: Peer review

### ISSUE THREAD

**Issue by Ismailco** [ahangarha/MV-ToDo-List#11]
Your code is good, clean code, and respect the best practices. but you can:
- It would be good to use destructuring in the class and functions.
- You can use default Parameters, for KISS best practices.
- Optional, it would be cleaner if you had a label with the id of the input type.
- Optional, I think you could have created a separated js file containing the addToPage function that will make your code look better and not overwhelming.
- Optional, I would suggest setting text-transform to capitalize as the user can enter words awkwardly.

**Comment by ahangarha** [comment]
Thank you guys.

I wish there was more specific details on deconstruction and KISS but I will take a look.

Regarding the suggestion on pulling `addToPage` method out of the class, I agree. I need to see how to do that.

Thanks again for your feedback
