### ISSUE TITLE
Suggestions for better implementation

### ISSUE THREAD

**Issue by souad988** [ahangarha/MV-ToDo-List#8]
Hello Mustafa
you did a great job implementing all the requirement 
and I suggest that you use a separate class for the logic part (CRUD functionalities) and also for the DOM this way you can implement the tests easily by calling methods. and also if you want to implement more functionalities you will not be lost between the lines
otherwise you did good

**Comment by ahangarha** [comment]
Thanks for the peer review.

I think I should see the the TodoList class as kind of DataBase (or somehow the model) layer. I should have a controller for connecting that to the DOM (view). Am I right? I thought about it many times but didn't reach to any conclusion.

**Comment by Ismailco** [comment]
Your code is clean and very organized @ahangarha
As @souad988 mentioned you could create a class just for the list and its methods (add, remove, update). and another class for handling local storage and DOM manipulation.

**Comment by souad988** [comment]
> Thanks for the peer review.
> 
> I think I should see the the TodoList class as kind of DataBase (or somehow the model) layer. I should have a controller for connecting that to the DOM (view). Am I right? I thought about it many times but didn't reach to any conclusion.


**yes exactly**
